### ISSUE TITLE
TimeInstant init from SystemTimeProvider wrong

### ISSUE THREAD

**Issue by trongcauhcmus** [NemProject/nem.core#32]
i have issue when creating Transaction and using setDeadline function. after sendTransaction i get this result:
```
{"innerTransactionHash":{},"code":10,"type":1,"message":"FAILURE_TIMESTAMP_TOO_FAR_IN_FUTURE","transactionHash":{"data":"77a80545bb880fb743c1b7cdf3a56140c3febc14ea1d948c53d71619936beb4f"}}
```
When i debug to function
 `public TimeInstant getCurrentTime() {
        long time = System.currentTimeMillis() + timeOffset.getRaw();
        return new TimeInstant(getTime(time));
    }`
it get wrong value from `getTime` to `new TimeInstant`

**Comment by trongcauhcmus** [comment]
timestamp in my machine and timestamp in node server have a gap with 10s
when i create transaction, need to substract the timestamp to 10 and get success
Note: the transaction timestamp and server would not deviate 10s

**Comment by BloodyRookie** [comment]
that is exactly why you should use the **network** time. There is an api request for it:

/time-sync/network-time

so a full request would look like

http://hugealice.nem.ninja:7890/time-sync/network-time

which returns something like

{
   sendTimeStamp: 114611953917
   receiveTimeStamp: 114611953917
}

Take that timestamp divided by 1000 (because the timestamp is in ms instead of seconds) and your should be fine.
